### ISSUE TITLE
Update slotmap features

### ISSUE THREAD

**Issue by orlp** [LPGhatguy/thunderdome#15]
Hey, I'm the author of `slotmap`. I see you have a comparison table in your README.

Since `slotmap` 1.0 it supports `no_std` as well as non-`Copy` values for all data structures. I would appreciate it if you could update the table to reflect this in your next version.

**Comment by LPGhatguy** [comment]
Thanks for filing an issue! I just updated the repository's `lib.rs` and `README.md` files, and they'll be going up in the next release.
