### ISSUE TITLE
Iterator API design

### ISSUE THREAD

**Issue by toyboot4e** [LPGhatguy/thunderdome#19]
`thunderdome::Iter` returns `(Index, &T)` pair. Iterator of `&T` would also be useful.

`Arena` API design choices would be:

1. `iter` only
2. `iter` + `values`
3. `iter` + `indexed_values` (swapped version of 2.)

**Comment by LPGhatguy** [comment]
I think that because iterator adapters are easy in Rust, it's probably okay to have just the one type of iterator method for now.

We can revisit this in the future if the need arises. What do you think?

**Comment by toyboot4e** [comment]
Yes, it makes sense to me. Thank you for the clarification :)

**Comment by mikwielgus** [comment]
I have a library, [maplike](https://github.com/mikwielgus/maplike), that provides a generic interface over as many containers as possible, including `thunderdome::Arena`. For the purpose of its completion, it would be nice to have a values-only iteration capability in `thunderdome`.

Values-only iterators are usually created from a method called `.values()` (e.g. [BTreeMap::values()](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.values), [StableVec::values()](https://docs.rs/stable-vec/latest/stable_vec/struct.StableVecFacade.html#method.values)).

If you are interested, I can PR this.

**Comment by LPGhatguy** [comment]
Given the existence of the map-like `values()` iterators, I would totally accept a PR for that!
