### ISSUE TITLE
Add Arena::get2_mut(Index, Index) or similar methods

### ISSUE THREAD

**Issue by 01010101lzy** [LPGhatguy/thunderdome#21]
As one coming from `generational-arena`, I found `thunderdome` is lacking a method similar to [`Arena::get2_mut(&mut self, Index, Index) -> (Option<&mut Value>, Option<&mut Value>)`](https://docs.rs/generational-arena/0.2.8/generational_arena/struct.Arena.html#method.get2_mut).

This method allows library users to access two different values at once (as long as their indices are different), allowing one to perform complex operations efficiently. An example usage would be connecting doubly-linked lists inside this arena, where having mutable references of both lists' ends simplifies the code.

Taking this idea one step further, adding another method like `unsafe Arena::get_many_mut(&mut self, impl Iterator<Item=Index>) -> impl Iterator<Option<&mut Value>>` (where the user ensures no two indices are the same) also seems reasonable. I'm just not sure if it's really needed.

**Comment by LPGhatguy** [comment]
I would accept a PR for `Arena::get2_mut`. I think the more generalized form gets into hairy situations pretty easily, and we ought to be able to implement `get2_mut` with only safe code using [slice::split_first_mut](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.split_first_mut).
