### ISSUE TITLE
Consider exposing generation

### ISSUE THREAD

**Issue by shepmaster** [LPGhatguy/thunderdome#34]
I have a few `thunderdome::Arena`s so I'm wrapping the `Index` in my own newtypes to keep things manageable. That means that my `Debug` output looks like:

```
ElementIndex(Index { slot: 1, generation: Generation(2) })
```

I'd prefer to use something a bit shorter: 

```
ElementIndex(2, 1)
```

However, it's not possible to get the generation out of an `Index` for use in my own `Debug` implementation. I assume there's good reasons for that, so this suggestion may go nowhere, but it's worth asking!

**Comment by LPGhatguy** [comment]
I don't see why not! We could probably add a `generation(&self)` method to return the generation, probably no harm in doing so.

**Comment by shepmaster** [comment]
> it's not possible to get the generation out of an `Index`

I guess this isn't _technically_ true, as I could use `Index::to_bits` and extract the generation; that seems like reasonable justification that it could stand as a separate method.
